# Generated by Django 4.2 on 2023-04-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='api.country'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together={('country',)},
        ),
    ]
