# Generated by Django 4.2 on 2023-04-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.car'),
        ),
    ]
